### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Create Deposit Account Request
# @name createDepositAccount
POST {{host}}/Accounts_V1/createDepositAccount
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "AccountHolders": [
    {
      "AccountHolderId": 29960,
      "IsOrganization": false,
      "MembershipNumber": "",
      "SavingsACNumber": "T-0037417"
    }
  ],
  "Nominees": [
    {
       "NomineePercentage": 100,
      "PersonId": 52155
    }
  ],
  "AccountOperators": [
    {
       "AccountHolderId": 37425,
      "AccountOperatorId": 37425
    }
  ],
  "Introducers":[],
  "DMSProductCode":"20" ,
  "ApplicationNo":"",
  "BranchCode":"00",
  "AccountFor": 1,
  "AccountName": "RIPON  BAROI",
  "InterestRate": 8.5,
  "Duration": 60,
  "InstallmentAmount": 500,
  "RolePermissionId": "1,2,3",
  "UserId": 123,
  "TxnAccountNumber": "T-0051979",
  "InterestPostingAccount": "",
  "OTPRegId": "{{OTPRegId}}",
  "OTPValue": "{{OTPValue}}",
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "{{MobileNumber}}",
  "MobileNo": "{{MobileNumber}}",
  "RequestFrom":"{{RequestFrom}}"
}

### Response

{
  "transfer_from": {
    "from_account": {
      "id": 0,
      "account_number": "T-0051979"
    },
    "from_card": {
      "id": 0,
      "card_number": ""
    }
  },
  "account_details": {
    "product_code": "20",
    "account_for": 1,
    "account_name": "RIPON  BAROI",
    "interest_rate": 8.5,
    "duration": 60,
    "installment_amount": 500,
    "txn_account_number": "T-0051979",
    "interest_posting_account": ""
  },
  "account_holders": [
    {
      "account_holder_id": 29960,
      "is_organization": false,
      "membership_number": "",
      "savings_ac_number": "T-0037417",
      "account_name": "RIPON  BAROI"
    }
  ],
  "nominees": [
    {
      "person_id": 52155,
      "name": "",
      "nominee_percentage": 100
    }
  ],
  "account_operators": [
    {
      "account_holder_id": 37425,
      "account_operator_id": 37425,
      "operator_name": ""
    }
  ],
  "introducers": [
    {
      "account_holder_id": 0,
      "introducer_id": 0,
      "introducer_name": ""
    }
  ],
  "otp_details": {
    "otp_reg_id": "",
    "otp_value": ""
  }
}
